# Generated by Django 4.2.30 on 2026-06-29 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0002_user_employee_type_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyDatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Может'), ('UNAVAILABLE', 'Не может')], max_length=11)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='work_schedule.schedulemonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_date_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='unavailabledutydate',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvailableDutyDate',
        ),
        migrations.DeleteModel(
            name='UnavailableDutyDate',
        ),
    ]
