# Generated by Django 4.2.30 on 2026-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0004_shifttype_duty'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_duty_per_day'),
        ),
    ]
