# Generated by Django 4.2.30 on 2026-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0005_duty_unique_user_duty_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='required_people',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
