# Generated by Django 4.2.30 on 2026-07-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0006_duty_generated_shifttype_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('required_people', models.PositiveSmallIntegerField(default=1)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='work_schedule.schedulemonth')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_schedule.shifttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shiftrequirement',
            constraint=models.UniqueConstraint(fields=('date', 'shift_type'), name='unique_shift_requirement'),
        ),
    ]
