# Generated by Django 4.2.30 on 2026-07-12

from django.db import migrations, models


def mark_existing_long_shifts_as_weekend(apps, schema_editor):
    ShiftType = apps.get_model("work_schedule", "ShiftType")
    ShiftType.objects.filter(hours__gte=20).update(day_type="WEEKEND")


class Migration(migrations.Migration):

    dependencies = [
        ("work_schedule", "0007_shiftrequirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttype",
            name="day_type",
            field=models.CharField(
                choices=[("WEEKDAY", "Будни"), ("WEEKEND", "Выходные")],
                default="WEEKDAY",
                max_length=7,
                verbose_name="Дни применения",
            ),
        ),
        migrations.RunPython(mark_existing_long_shifts_as_weekend, migrations.RunPython.noop),
    ]
