# Generated by Django 4.2.30 on 2026-07-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_schedule", "0008_shifttype_day_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenceActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="preference_activities", to="work_schedule.schedulemonth")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="preference_activities", to="work_schedule.user")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "month"),
                        name="unique_preference_activity_per_month",
                    ),
                ],
            },
        ),
    ]
