# Generated by Django 4.2.30 on 2026-07-12 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0009_preferenceactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemonth',
            name='increased_staff_count',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сотрудников в выбранные дни'),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='increased_staff_weekdays',
            field=models.CharField(default='1,4', help_text='Дни недели в служебном формате, выбираются в форме администратора.', max_length=13, verbose_name='Дни с увеличенным составом'),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='part_time_allowed_weekdays',
            field=models.CharField(default='1,4', help_text='Дни недели в служебном формате, выбираются в форме администратора.', max_length=13, verbose_name='Разрешённые дни совместителей'),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='part_time_hours_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Норма совместителя, %'),
        ),
    ]
