# Generated by Django 4.2.30 on 2026-07-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0010_schedulemonth_increased_staff_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True, help_text='Отключите для отдельной учётной записи администратора.', verbose_name='Участвует в графике'),
        ),
    ]
