# Generated by Django 4.2.30 on 2026-07-14 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0015_team_registration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('absence_type', models.CharField(choices=[('VACATION', 'Отпуск'), ('SICK', 'Больничный'), ('TRAINING', 'Обучение')], default='VACATION', max_length=8, verbose_name='Причина отсутствия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_absences', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отсутствие сотрудника',
                'verbose_name_plural': 'Отсутствия сотрудников',
                'ordering': ('date', 'user__full_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='employeeabsence',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_employee_absence_date'),
        ),
    ]
